name: Fetch Modified Files

on:
  push:
    branches:
      - main

jobs:
  fetch-modified-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get the list of modified files
      id: modified_files
      run: |
        git fetch --depth=2 origin main
        BASE_COMMIT=$(git rev-parse HEAD^1 || echo "")
        if [ -z "$BASE_COMMIT" ]; then
          echo "No previous commit found. Only one commit in the repository."
          MODIFIED_FILES=""
        else
          MODIFIED_FILES=$(git diff --name-only $BASE_COMMIT HEAD)
        fi
        echo "::set-output name=files::$MODIFIED_FILES"

    - name: Display modified files
      run: |
        echo "Modified files: ${{ steps.modified_files.outputs.files }}"
